import Foundation
@preconcurrency import SocketIO

/// A unified, typed error surface for `SocketIOConcurrency`.
///
/// This type normalizes errors from the underlying `socket.io-client-swift`
/// callbacks (`.error`, disconnect reasons, ack timeout sentinels) and errors
/// produced by this package's async/await layer.
public extension SocketIOClient {
    enum Error: Swift.Error, Sendable, Equatable {
        /// A classified origin of a client-level error message.
        public enum Source: String, Sendable, Equatable {
            /// Generic Socket.IO client layer.
            case socketIO
            /// Engine-level failures (connection engine/session/protocol internals).
            case engine
            /// Transport-level failures (websocket/polling/transport switching).
            case transport
            /// Application-level failures generated by this package.
            case application
        }

        /// The operation was cancelled.
        case cancelled
        /// The provided timeout is invalid.
        ///
        /// Expected timeout values are greater than zero.
        case invalidTimeout(TimeInterval)
        /// The client is not connected for the requested event operation.
        ///
        /// - Parameter event: Event name that was attempted.
        case notConnected(event: String)
        /// The server did not acknowledge an emitted event before timeout.
        ///
        /// - Parameters:
        ///   - event: Event name that was emitted.
        ///   - timeout: Timeout used for waiting for the acknowledgement.
        case ackTimedOut(event: String, timeout: TimeInterval)
        /// The socket disconnected while listening for an event.
        ///
        /// - Parameters:
        ///   - event: Event stream that was active.
        ///   - reason: Optional disconnect reason from the underlying client.
        case disconnected(event: String, reason: String?)
        /// A normalized client error with classified source and message.
        ///
        /// - Parameters:
        ///   - event: Optional event context associated with the error.
        ///   - message: Human-readable error message.
        ///   - source: Error origin classification.
        case clientError(event: String?, message: String, source: Source)
        /// Failed to transform outgoing socket data into a valid representation.
        ///
        /// - Parameters:
        ///   - event: Optional event context associated with the failure.
        ///   - message: Human-readable conversion error.
        case invalidSocketData(event: String?, message: String)
        /// Encountered a payload value that can't be converted to `Sendable`.
        ///
        /// - Parameter typeName: Runtime type name of the unsupported payload value.
        case unsupportedPayloadType(typeName: String)
        /// Encountered a dictionary key that isn't a `String` during payload conversion.
        ///
        /// - Parameter typeName: Runtime type name of the unsupported key.
        case unsupportedDictionaryKeyType(typeName: String)
    }
}

extension SocketIOClient.Error {
    init(clientEventPayload data: [Any], fallbackEvent: String?) {
        let eventName = fallbackEvent ?? (data.first as? String)

        if let firstMessage = data.first as? String, data.count == 1 {
            if firstMessage == "Tried emitting when not connected" {
                self = .notConnected(event: fallbackEvent ?? eventName ?? "<unknown>")
                return
            }

            self = .clientError(
                event: fallbackEvent,
                message: firstMessage,
                source: Self.inferSource(from: firstMessage)
            )
            return
        }

        if data.count >= 3, let event = data[0] as? String, let error = data[2] as? any Swift.Error {
            self = .init(thrown: error, event: event)
            return
        }

        if let trailingError = data.last as? any Swift.Error {
            self = .init(thrown: trailingError, event: eventName)
            return
        }

        let message = data.map { String(describing: $0) }.joined(separator: " ")
        if message.contains("not connected") {
            self = .notConnected(event: fallbackEvent ?? eventName ?? "<unknown>")
            return
        }

        self = .clientError(
            event: eventName,
            message: message.isEmpty ? "Socket.IO client error" : message,
            source: .socketIO
        )
    }

    init(thrown error: any Swift.Error, event: String?) {
        if let error = error as? SocketIOClient.Error {
            self = error
            return
        }

        if error is CancellationError {
            self = .cancelled
            return
        }

        let message = (error as NSError).localizedDescription
        self = .invalidSocketData(event: event, message: message)
    }

    init?(ackData data: [Any], event: String, timeout: TimeInterval) {
        guard let first = data.first as? String else {
            return nil
        }

        guard first == SocketAckStatus.noAck.rawValue else {
            return nil
        }

        self = .ackTimedOut(event: event, timeout: timeout)
    }

    private static func inferSource(from message: String) -> Source {
        let lowered = message.lowercased()
        if lowered.contains("engine") {
            return .engine
        }

        if lowered.contains("websocket") || lowered.contains("poll") || lowered.contains("transport") {
            return .transport
        }

        return .socketIO
    }
}
